/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Angles;

/**
 *
 * @author erhal8376
 */
public class FormAngles extends javax.swing.JFrame {

    /**
     * Creates new form FormAngles
     */
    public FormAngles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        angleField = new javax.swing.JTextField();
        anglePrompt = new javax.swing.JLabel();
        sideField1 = new javax.swing.JTextField();
        sideField2 = new javax.swing.JTextField();
        sidePrompt1 = new javax.swing.JLabel();
        sidePrompt2 = new javax.swing.JLabel();
        sinButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        sinInvButton = new javax.swing.JButton();
        cosInvButton = new javax.swing.JButton();
        tanInvButton = new javax.swing.JButton();
        output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        angleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angleFieldActionPerformed(evt);
            }
        });

        anglePrompt.setText("Enter Angle:");

        sideField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideField1ActionPerformed(evt);
            }
        });

        sideField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideField2ActionPerformed(evt);
            }
        });

        sidePrompt1.setText("Enter Side 1:");

        sidePrompt2.setText("Enter Side 2:");

        sinButton.setText("Sin");
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });

        tanButton.setText("Tan");
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });

        cosButton.setText("Cos");
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        sinInvButton.setText("Sin Inv");
        sinInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinInvButtonActionPerformed(evt);
            }
        });

        cosInvButton.setText("Cos Inv");
        cosInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosInvButtonActionPerformed(evt);
            }
        });

        tanInvButton.setText("Tan Inv");
        tanInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanInvButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anglePrompt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sidePrompt1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sidePrompt2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sideField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sideField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sinInvButton)
                                    .addComponent(sinButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cosButton)
                                    .addComponent(cosInvButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanButton)
                                    .addComponent(tanInvButton))))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anglePrompt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sideField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidePrompt1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sideField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidePrompt2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinButton)
                    .addComponent(cosButton)
                    .addComponent(tanButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinInvButton)
                    .addComponent(cosInvButton)
                    .addComponent(tanInvButton))
                .addGap(18, 18, 18)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void angleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angleFieldActionPerformed

    private void sideField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideField1ActionPerformed

    private void sideField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideField2ActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
        double degVal = Double.parseDouble(angleField.getText());
        double radVal = Math.toRadians(degVal);
        radVal = Math.sin(radVal);
        radVal = Math.round(radVal*100);
        radVal = radVal / 100;
        output.setText(Double.toString(radVal));
    }//GEN-LAST:event_sinButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
        double degVal = Double.parseDouble(angleField.getText());
        double radVal = Math.toRadians(degVal);
        radVal = Math.cos(radVal);
        radVal = Math.round(radVal*100);
        radVal = radVal / 100;
        output.setText(Double.toString(radVal));
    }//GEN-LAST:event_cosButtonActionPerformed

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtonActionPerformed
        double degVal = Double.parseDouble(angleField.getText());
        double radVal = Math.toRadians(degVal);
        radVal = Math.tan(radVal);
        radVal = Math.round(radVal*100);
        radVal = radVal / 100;
        output.setText(Double.toString(radVal));
    }//GEN-LAST:event_tanButtonActionPerformed

    private void sinInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinInvButtonActionPerformed
        double radVal = Math.asin(Double.parseDouble(sideField1.getText()) / Double.parseDouble(sideField2.getText()));
        radVal = Math.toDegrees(radVal);
        radVal = Math.round(radVal*10);
        radVal = radVal / 10;
        output.setText(Double.toString(radVal) + " degrees");
    }//GEN-LAST:event_sinInvButtonActionPerformed

    private void cosInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosInvButtonActionPerformed
        double radVal = Math.acos(Double.parseDouble(sideField1.getText()) / Double.parseDouble(sideField2.getText()));
        radVal = Math.toDegrees(radVal);
        radVal = Math.round(radVal*10);
        radVal = radVal / 10;
        output.setText(Double.toString(radVal) + " degrees");
    }//GEN-LAST:event_cosInvButtonActionPerformed

    private void tanInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanInvButtonActionPerformed
        double radVal = Math.atan(Double.parseDouble(sideField1.getText()) / Double.parseDouble(sideField2.getText()));
        radVal = Math.toDegrees(radVal);
        radVal = Math.round(radVal*10);
        radVal = radVal / 10;
        output.setText(Double.toString(radVal) + " degrees");
    }//GEN-LAST:event_tanInvButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAngles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angleField;
    private javax.swing.JLabel anglePrompt;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton cosInvButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output;
    private javax.swing.JTextField sideField1;
    private javax.swing.JTextField sideField2;
    private javax.swing.JLabel sidePrompt1;
    private javax.swing.JLabel sidePrompt2;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sinInvButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JButton tanInvButton;
    // End of variables declaration//GEN-END:variables
}
